# Generated by Django 4.1 on 2023-05-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_username'),
    ]

    operations = [
    ]
